---
title: "TSAR Data Preprocessing and Analysis Workflow"
author: "Candy Gao"
date: "4/8/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(devtools)
devtools::install_local("/Users/candygao/Desktop/TSAR_0.1.0.tar.gz")
library(TSAR)
library(dplyr)
library(ggplot2)
```

## load data

```{r}
#raw_data <- read.delim(header = TRUE, skip = 0, nrow = 112976, "/Users/candygao/Desktop/qpcrresult/CA_IP_HCB_2_20220110_134917_RawData_Thermal Shift_02_55.eds.txt")
raw_data <- read.delim(header = TRUE, skip = 1, file = "/Users/candygao/Desktop/raw.txt")
```

## select individual cell for analysis

```{r}
test <- raw_data %>%
  filter(Well.Position == "A3") # select data for one well by well ID

#section data by temperature to remove messy area
#test <- subset(test, test$Temperature>40 & test$Temperature <50) 

test <- normalize(data = test, Fluo = 5, selected = c("Well.Position", "Temperature", "Fluorescence", "Normalized")) 
head(test)
gammodel <- model_gam(Data = test, x = test$Temperature, y = test$Normalized)
test <- modelfit(data = test, model = gammodel)

#if dataset is already smoothed
#test <- mutate(test, norm_deriv = c(diff(test$Fluorescence)/diff(test$Temperature),NA))

tm_est(test)


#graphing
result <- ggplot(data = test, aes(x = Temperature, y = Normalized)) +
  geom_point(shape = 1)+ #normalized data
  geom_point(aes(y=fitted), color = "blue", alpha = 1/10)+ #fitted value
  geom_vline(xintercept = tm_est(test), color = "red") #tm temperature value

result

```

## 96 well application

```{r}
#run analysis
x <- gam_analysis(raw_data, smoothed = T, selections = c("Well.Position", "Temperature", "Fluorescence", "Normalized"))

#write output data file
write.tsar(read.tsar(x, code = 2), name = "tm_val", file = "csv")

#look at only tm result by well
output <- read.tsar(x, code = 0)
head(output)
tail(output)

#join protein and ligand information 
tmresult <- join.well_info("/Users/candygao/Desktop/qpcrresult/Well Information Template.xlsx", output, type = "by_template")
head(tmresult)
```
