---
title: "SuFEX_Suppl"
author: "William McFadden"
date: "12/13/2021"
output: html_document
---

```{r}
devtools::load_all()

library(ggplot2)
library(ggpubr)
library(readxl)
library(stringr)
library(tidyr)
library(dplyr)
library(readr)
library(mgcv)
```




```{r}
analysis_paths <- 
    c("/Users/billy/Desktop/SGS_Lab/TSA/8.3.21/WM_20210803_BBS_CAFL_ON_Conc_2_20210804_124320_AnalysisResults.csv",
      "/Users/billy/Desktop/SGS_Lab/TSA/8.2.21/WM_20210802_BBS_CAFL_ON_Conc_20210803_144732_AnalysisResults.csv")


raw_paths <- 
    c("/Users/billy/Desktop/SGS_Lab/TSA/8.3.21/WM_20210803_BBS_CAFL_ON_Conc_2_20210804_124320_RawData_WM_20210803_BBS_CAFL_ON_Conc_2_compOnly.eds.txt",
      "/Users/billy/Desktop/SGS_Lab/TSA/8.2.21/WM_20210802_BBS_CAFL_ON_Conc_20210803_144732_RawData_WM_20210802_BBS_CAFL_ON_Conc.eds.csv")



tsa_sufex <- 
merge_TSA(
    raw_data_path = raw_paths, 
    analysis_file_path = analysis_paths)
head(tsa_sufex)
```


```{r}
condition_IDs(tsa_sufex)
```




```{r}
TSA_Tms(tsa_sufex)
```






```{r}
tsa_sufex <- normalize_fluorescence(tsa_sufex)
head(tsa_sufex)
```


```{r}
for(i in 1:condition_IDs(tsa_sufex, n = TRUE)) {
    cond_i <- condition_IDs(tsa_sufex)[i]
    subset_i <- tsa_sufex$condition_ID == cond_i
    subset_i <- tsa_sufex[subset_i, ]
    plot_i <- TSA_wells_plot(subset_i,
                             y = "Fluorescence", 
                             show_average = TRUE,
                             separate_legend = FALSE)
    
    
    print(plot_i)
}
```


```{r}
tsa_compare_plot(tsa_sufex,
                 y = "Fluorescence",
                 control_condition = "CA-FL_DMSO",
                 show_Tm = FALSE)
```







```{r}
tsa_sufex_subset <- tsa_sufex
    #tsa_sufex[tsa_sufex$Protein == "Buffer", ]

for(i in 1:condition_IDs(tsa_sufex_subset, n = TRUE)) {
    cond_i <- condition_IDs(tsa_sufex_subset)[i]
    subset_i <- tsa_sufex$condition_ID == cond_i
    subset_df_i <- tsa_sufex[subset_i, ]    
    
    #-- Get control ID
    ligand_i <- TSA_ligands(subset_df_i) #get condition
    control_df_filter_1 <- tsa_sufex$Ligand == ligand_i
    control_df_i <- tsa_sufex[control_df_filter_1, ]
    control_df_filter_2 <- control_df_i$Protein == "CA-FL"
    control_df_i <- control_df_i[control_df_filter_2, ]
    control_cond_i <- condition_IDs(control_df_i)
    
    #-- Get DF
    filter_3 <- tsa_sufex$Ligand == ligand_i
    subset_df_i <- tsa_sufex[filter_3, ]
    
    
    if(length(control_cond_i) > 1){
        print("control_cond_i > 1")
    }

    plot_i <- tsa_compare_plot(subset_df_i,
                 y = "Fluorescence",
                 control_condition = control_cond_i) 
    
    
    
    print(plot_i)
}


```





