#' TSAR Condition IDs
#'
#' This function is used to extract information of the condition IDs from a
#'   loaded TSA Analysis Data file. Condition IDs are automatically generated
#'   by the read_analysis function in the automated workflow. This returns
#'   either a character vector of unique IDs present or a numeric value of the
#'   number of unique IDs.
#'
#'
#' @param analysis_data a data frame that is unmerged and generated by
#'  TSAR::read_analysis() or a merged TSA data frame generated by
<<<<<<< HEAD
#'  TSAR::merge_TSA(). Data frames require a column named 'condition_ID'.
=======
#'  TSAR::merge_tsa(). Data frames require a column named 'condition_ID'.
>>>>>>> main
#' @param n logical value; \code{n = FALSE} by default. When TRUE, a numeric
#' value of unique IDs is returned. When FALSE, a character vector of unique
#' IDs are returned.
#'
#' @return Either a character vector of condition_IDs or a numeric value.
#'
#'
#' @family TSA Summary Functions
<<<<<<< HEAD
#' @seealso \code{\link{merge_TSA}} and \code{\link{read_analysis}}
=======
#' @seealso \code{\link{merge_tsa}} and \code{\link{read_analysis}}
>>>>>>> main
#' for preparing input.
#' @export
#'
condition_IDs <- function(
    analysis_data, #analysis data to determine number of unique conditions
    n = FALSE #c("T", "F") F = vector, T = number summary
<<<<<<< HEAD
){
    if(n){
=======
) {
    if (n) {
>>>>>>> main
        return(length(unique(analysis_data$condition_ID)))
    } else {
        return(unique(analysis_data$condition_ID))
    }
}




#' TSAR Well IDs
#'
#' This function is used to extract information of the well IDs from a
#'   merged TSA data frame. Well IDs are automatically generated
#'   by the read_analysis and read_raw_data functions in the automated workflow.
#'   This function returns
#'   either a character vector of unique IDs present or a numeric value of the
#'   number of unique IDs.
#'
#'
#' @param tsa_data a data frame that is merged and generated by
<<<<<<< HEAD
#'   TSAR::merge_TSA(), or an unmerged data frame read by TSAR::read_analysis()
=======
#'   TSAR::merge_tsa(), or an unmerged data frame read by TSAR::read_analysis()
>>>>>>> main
#'   or TSAR::read_raw_data().
#'   Data frames require a column named 'well_ID'.
#' @param n logical value; \code{n = FALSE} by default. When TRUE, a numeric
#' value of unique IDs is returned. When FALSE, a character vector of unique
#' IDs are returned.
#'
#' @return Either a character vector of unique well IDs or a numeric value.
#'
#' @family TSA Summary Functions
<<<<<<< HEAD
#' @seealso \code{\link{merge_TSA}}, \code{\link{read_raw_data}},
=======
#' @seealso \code{\link{merge_tsa}}, \code{\link{read_raw_data}},
>>>>>>> main
#' and \code{\link{read_analysis}} for preparing input.
#'
#' @export

well_IDs <- function(
    tsa_data, #tsa data to determine number of unique conditions
    n = FALSE #c("T", "F") F = List, T = number summary
<<<<<<< HEAD
){
    if(n){
=======
) {
    if (n) {
>>>>>>> main
        return(length(unique(tsa_data$well_ID)))
    } else {
        return(unique(tsa_data$well_ID))
    }
}

#' TSA Proteins
#'
#' This function is used to extract information from a data frame of TSA data.
#'   The Protein values should be assigned in the TSA software.
#'
#' @param tsa_data a data frame that is merged and generated by
<<<<<<< HEAD
#'   TSAR::merge_TSA(), or an unmerged data frame read by TSAR::read_analysis()
=======
#'   TSAR::merge_tsa(), or an unmerged data frame read by TSAR::read_analysis()
>>>>>>> main
#'   or TSAR::read_raw_data().
#'   The data frame must have a column named 'Protein'.
#' @param n logical value; \code{n = FALSE} by default. When TRUE, a numeric
#'  value describing the number of unique protein names is returned.
#'  When FALSE, a character vector of unique IDs are returned.
#'
#' @return Either a character vector of unique well_IDs or a numeric value.
#'
#' @family TSA Summary Functions
<<<<<<< HEAD
#' @seealso \code{\link{merge_TSA}}, \code{\link{read_raw_data}},
=======
#' @seealso \code{\link{merge_tsa}}, \code{\link{read_raw_data}},
>>>>>>> main
#' and \code{\link{read_analysis}} for preparing input.
#'
#' @export

TSA_proteins <- function(
    tsa_data, #tsa data to determine number of unique conditions
    n = FALSE #c("T", "F") F = List, T = number summary
<<<<<<< HEAD
){
    if(n){
=======
) {
    if (n) {
>>>>>>> main
        return(length(unique(tsa_data$Protein)))
    } else {
        return(unique(tsa_data$Protein))
    }
}

#' TSA Ligands
#'
#' This function is used to extract information from a data frame of TSA data.
#'   The Ligand values should be assigned in the TSA software.
#'
#' @param tsa_data a data frame that is merged and generated by
<<<<<<< HEAD
#'   TSAR::merge_TSA(), or an unmerged data frame read by TSAR::read_analysis()
=======
#'   TSAR::merge_tsa(), or an unmerged data frame read by TSAR::read_analysis()
>>>>>>> main
#'   or TSAR::read_raw_data().
#'   The data frame must have a column named 'Ligand'.
#' @param n logical value; \code{n = FALSE} by default. When TRUE, a numeric
#'  value describing the number of unique ligand names is returned.
#'  When FALSE, a character vector of unique IDs are returned.
#' @return Either a character vector of unique well_IDs or a numeric value.
#' @family TSA Summary Functions
<<<<<<< HEAD
#' @seealso \code{\link{merge_TSA}}, \code{\link{read_raw_data}},
=======
#' @seealso \code{\link{merge_tsa}}, \code{\link{read_raw_data}},
>>>>>>> main
#' and \code{\link{read_analysis}} for preparing input.
#'
#' @export

TSA_ligands <- function(
    tsa_data, #tsa data to determine number of unique conditions
    n = FALSE #c("T", "F") F = List, T = number summary
<<<<<<< HEAD
){
    if(n){
=======
) {
    if (n) {
>>>>>>> main
        return(length(unique(tsa_data$Ligand)))
    } else {
        return(unique(tsa_data$Ligand))
    }
}
